name: Build PR Docker image

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: pr-${{ github.event.pull_request.number }}

jobs:
  build-pr-image:
    runs-on: ubuntu-latest

    if: github.event.pull_request.draft == false

    permissions:
      contents: read
      packages: write
      pull-requests: write

    concurrency:
      group: docker-pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}
            type=sha,prefix=pr-${{ github.event.pull_request.number }}-

      - name: Prepare app version
        id: app-version
        shell: bash
        run: |
          short_sha="${GITHUB_SHA::7}"
          echo "version=pr-${{ github.event.pull_request.number }}-${short_sha}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=${{ steps.app-version.outputs.version }}
            APP_SOURCE_URL=${{ github.server_url }}/${{ github.repository }}
            VCS_REF=${{ github.sha }}

      - name: Post OCI image details
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5 
        with:
          header: docker-info
          message: |
            ### OCI Image created!
            
            The following details for the image are available:
            * **Tags:** `${{ steps.app-version.outputs.version }}` `pr-${{ github.event.pull_request.number }}`
            * **Image:** `ghcr.io/${{ github.repository }}:${{ steps.app-version.outputs.version }}`
            * **Digest:** `${{ steps.docker_build.outputs.digest }}`
            <details>
            <summary>**Metadata**</summary>
            ```json
            ${{ steps.docker_build.outputs.metadata }}
            ```
            </details>

            

            